---
configs:
  use: 'sw-dev'
  sw-dev:
    vm_ip: '192.168.178.111'
    vm_hostname: 'sw-dev'
    vm_url: 'sw.dev'
    vm_name: 'sw-dev'
    db_name: 'shopware'
    db_user: 'dbuser'
    db_pass: 'passwort'
