---
configs:
  use: 'swdev'
  swdev:
    vm_ip: '192.168.178.178'
    vm_hostname: 'swdev'
    vm_url: 'sw.dev'
    vm_name: 'swdev'
    db_name: 'shopware'
    db_user: 'admin'
    db_pass: 'passwort'
