---
configs:
  use: 'devbox'
  devbox:
    vm_ip: '192.168.178.88'
    vm_hostname: 'devbox'
    vm_url: 'devbox.local'
    vm_name: 'devbox'
    db_name: 'testdb'
    db_user: 'dbuser'
    db_pass: 'passwort'
